force-app/main/default/objects/Launchpad__Job__c/Launchpad__Job__c.object-meta.xml
<CustomObject>
    <description>This Object is used by Employers to create Job positions that are open for hire.</description>
    <label>Job</label>
    <nameField>
        <label>Job Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Launchpad__Job__c/fields/Ages_Served__c.field-meta.xml
<CustomField>
    <fullName>Ages_Served__c</fullName>
    <label>Ages Served</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Launchpad__Job__c/fields/Gender_Served__c.field-meta.xml
<CustomField>
    <fullName>Gender_Served__c</fullName>
    <inlineHelpText>If only one gender served</inlineHelpText>
    <label>Gender Served</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Launchpad__Job__c/fields/Genders_Served__c.field-meta.xml
<CustomField>
    <fullName>Genders_Served__c</fullName>
    <label>Genders Served</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Launchpad__Job__c/fields/Grades_Served__c.field-meta.xml
<CustomField>
    <fullName>Grades_Served__c</fullName>
    <label>Grades Served</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grades</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Launchpad__Job__c/fields/Job_Site_Address__c.field-meta.xml
<CustomField>
    <fullName>Job_Site_Address__c</fullName>
    <formula>Placement_Site__r.ShippingStreet</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Job Site Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Launchpad__Job__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Launchpad__Program__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Launchpad__Program__c/Launchpad__Program__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track programs awarded to the organization i.e. WIOA Adult, TAA, etc.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Grades.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <masterLabel>Grades</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProviderSearchController.cls
public with sharing class ProviderSearchController {
    @AuraEnabled(cacheable=true)
    public static List<Launchpad__Job__c> searchJobs(String zipCode, List<String> age, List<String> grade, String gender) {
        String searchQuery = '';

        if (zipCode != null) {
            searchQuery = ' AND Job_Site__r.Job_Site_Address__c CONTAINS :zipCode';
        }

        if (age != null && !age.isEmpty()) {
            searchQuery = ' AND Ages_Served__c INCLUDES :age';
        }

        if (grade != null && !grade.isEmpty()) {
            searchQuery = ' AND Grades_Served__c INCLUDES :grade';
        }

        if (gender != null) {
            searchQuery = ' AND Genders_Served__c INCLUDES :gender';
        }

        System.debug('QUERIED!!!' + searchQuery);
        
        String query = 'SELECT Id, Name, Ages_Served__c, Grades_Served__c, Gender_Served__c, Launchpad__Account__r.BillingStreet, Launchpad__Account__r.BillingCity, Launchpad__Account__r.BillingState, Launchpad__Account__r.BillingPostalCode, Job_Site__r.BillingStreet, Job_Site__r.BillingCity, Job_Site__r.BillingState, Job_Site__r.BillingPostalCode FROM Launchpad__Job__c WHERE Program__r.Launchpad__Active__c = \'Yes\'' + searchQuery;
        System.debug('final query: ' + query);
        return Database.query(query);
    }
}