force-app/main/default/objects/Launchpad__Job__c/Launchpad__Job__c.object-meta.xml
<CustomObject>
    <description>This Object is used by Employers to create Job positions that are open for hire.</description>
    <label>Job</label>
    <nameField>
        <label>Job Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Launchpad__Job__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Launchpad__Program__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Launchpad__Program__c/Launchpad__Program__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track programs awarded to the organization i.e. WIOA Adult, TAA, etc.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProviderJobsController.cls
/**
 * Created by holden on 3/20/25.
 */

public with sharing class ProviderJobsController {

    @AuraEnabled(Cacheable = true)
    public static Launchpad__Job__c[] getJobs(Id accountId) {
        return [
                SELECT Id, Name, Program__r.Name, Launchpad__Contact__r.Name
                FROM Launchpad__Job__c WHERE Launchpad__Account__c = :accountId
        ];
    }

    @AuraEnabled
    public static Launchpad__Job__c getJob(Id jobId, String fieldSetName) {
        ProviderSearchController.FieldData[] fieldData = ProviderSearchController.getJobFieldSetMembers(fieldSetName);
        String query = 'SELECT Id, ';
        for (ProviderSearchController.FieldData data : fieldData) {
            query += data.apiName + ', ';
            if (data.type == 'REFERENCE') {
                query += data.apiName.replace('__c', '__r') + '.Name, ';
            }
        }
        query = query.removeEnd(', ');
        query += ' FROM Launchpad__Job__c WHERE Id = :jobId';
        return Database.query(query);
    }

    @AuraEnabled
    public static Map<String, Object> updateJob(Launchpad__Job__c job) {
        Map<String, Object> result = new Map<String, Object>();
        try {
            update job;
            result.put('success', 'Program saved successfully.');
        } catch (Exception e) {
            result.put('error', e.getMessage());
        }
        return result;
    }

}