force-app/main/default/objects/Launchpad__Job__c/Launchpad__Job__c.object-meta.xml
<CustomObject>
    <description>This Object is used by Employers to create Job positions that are open for hire.</description>
    <label>Job</label>
    <nameField>
        <label>Job Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Launchpad__Job__c/fields/Ages_Served__c.field-meta.xml
<CustomField>
    <fullName>Ages_Served__c</fullName>
    <label>Ages Served</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Launchpad__Job__c/fields/Genders_Served__c.field-meta.xml
<CustomField>
    <fullName>Genders_Served__c</fullName>
    <label>Genders Served</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Launchpad__Job__c/fields/Grades_Served__c.field-meta.xml
<CustomField>
    <fullName>Grades_Served__c</fullName>
    <label>Grades Served</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grades</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Launchpad__Job__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Launchpad__Program__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Launchpad__Job__c/fields/Schools_Served__c.field-meta.xml
<CustomField>
    <fullName>Schools_Served__c</fullName>
    <inlineHelpText>Only select schools if this Job is not applicable to all schools.</inlineHelpText>
    <label>Schools Served</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Schools</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Launchpad__Program__c/Launchpad__Program__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track programs awarded to the organization i.e. WIOA Adult, TAA, etc.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Grades.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <masterLabel>Grades</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Schools.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Other</fullName>
        <default>true</default>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>Academy at Palumbo</fullName>
    </customValue>
    <customValue>
        <fullName>Academy for the Middle Years (AMY) at Northwest</fullName>
    </customValue>
    <customValue>
        <fullName>Achieve Academy</fullName>
    </customValue>
    <customValue>
        <fullName>Achieve Academy East</fullName>
    </customValue>
    <customValue>
        <fullName>Ad Prima Charter School</fullName>
    </customValue>
    <customValue>
        <fullName>Adaire, Alexander School</fullName>
    </customValue>
    <customValue>
        <fullName>Allen, Dr. Ethel School</fullName>
    </customValue>
    <customValue>
        <fullName>Allen, Ethan School</fullName>
    </customValue>
    <customValue>
        <fullName>Allen, Richard Preparatory Charter School</fullName>
    </customValue>
    <customValue>
        <fullName>Alliance For Progress Charter School</fullName>
    </customValue>
    <customValue>
        <fullName>Alternative Middle Years (AMY) at James Martin</fullName>
    </customValue>
    <customValue>
        <fullName>Anderson, Add B. School</fullName>
    </customValue>
    <customValue>
        <fullName>Anderson, Marian Neighborhood Academy</fullName>
    </customValue>
    <customValue>
        <fullName>Arts Academy at Benjamin Rush</fullName>
    </customValue>
    <customValue>
        <fullName>Bache-Martin School</fullName>
    </customValue>
    <customValue>
        <fullName>Baldi Middle School</fullName>
    </customValue>
    <customValue>
        <fullName>Barry, John Elementary School</fullName>
    </customValue>
    <customValue>
        <fullName>Barton, Clara School</fullName>
    </customValue>
    <customValue>
        <fullName>Bartram, John High School</fullName>
    </customValue>
    <customValue>
        <fullName>Belmont Charter School</fullName>
    </customValue>
    <customValue>
        <fullName>Bethune, Mary M. School</fullName>
    </customValue>
    <customValue>
        <fullName>Blaine, James G. School</fullName>
    </customValue>
    <customValue>
        <fullName>Blankenburg, Rudolph School</fullName>
    </customValue>
    <customValue>
        <fullName>Bodine, William W. High School</fullName>
    </customValue>
    <customValue>
        <fullName>Boys Latin of Philadelphia Charter School</fullName>
    </customValue>
    <customValue>
        <fullName>Bracetti, Mariana Academy Charter School</fullName>
    </customValue>
    <customValue>
        <fullName>Bregy, F. Amedee School</fullName>
    </customValue>
    <customValue>
        <fullName>Bridesburg School</fullName>
    </customValue>
    <customValue>
        <fullName>Brown, Henry A. School</fullName>
    </customValue>
    <masterLabel>Schools</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProviderSearchControllerTest.cls
@IsTest
private class ProviderSearchControllerTest {

	@TestSetup
	static void createJobs() {
		List<Account> accounts = new List<Account>();
		accounts.add(new Account(Name = 'Test Account 1'));
        accounts.add(new Account(Name = 'Test Account 2', BillingPostalCode = '19104'));
		insert accounts;

		Launchpad__Program__c program = new Launchpad__Program__c(
			Name = 'Test Program 1',
			Launchpad__Active__c = 'Yes'
		);
		insert program;

		List<Launchpad__Job__c> jobs = new List<Launchpad__Job__c>();
		jobs.add(
			new Launchpad__Job__c(
				Name = 'Test Job 1',
				Launchpad__Account__c = accounts[0].Id,
				Launchpad__Available_in_Community__c = true,
				Program__c = program.Id,
				Launchpad__Job_Description__c = 'Test Description 1',
				Ages_Served__c = '12;13',
				Grades_Served__c = '7;8',
                Genders_Served__c = 'Male'
			)
		);
		jobs.add(
			new Launchpad__Job__c(
				Name = 'Test Job Zip 19104',
				Launchpad__Account__c = accounts[1].Id,
				Launchpad__Available_in_Community__c = true,
				Program__c = program.Id,
				Launchpad__Job_Description__c = 'Test Description 1',
				Ages_Served__c = '13;14',
				Grades_Served__c = '7;8',
                Genders_Served__c = 'Male'
			)
		);
        jobs.add(
			new Launchpad__Job__c(
				Name = 'Test Job 3',
				Launchpad__Account__c = accounts[0].Id,
				Launchpad__Available_in_Community__c = true,
				Program__c = program.Id,
				Launchpad__Job_Description__c = 'Test Description 1',
				Ages_Served__c = '13;14',
				Grades_Served__c = '6;7;8;',
                Genders_Served__c = 'Male'
			)
		);
        jobs.add(
			new Launchpad__Job__c(
				Name = 'Test Job AMY at James Martin',
				Launchpad__Account__c = accounts[0].Id,
				Launchpad__Available_in_Community__c = true,
				Program__c = program.Id,
				Launchpad__Job_Description__c = 'Test Description 1',
				Ages_Served__c = '13;14;15',
				Grades_Served__c = '7;8',
                Genders_Served__c = 'Male'
			)
		);
        jobs.add(
			new Launchpad__Job__c(
				Name = 'Test Job Females',
				Launchpad__Account__c = accounts[0].Id,
				Launchpad__Available_in_Community__c = true,
				Program__c = program.Id,
				Launchpad__Job_Description__c = 'Test Description 1',
				Ages_Served__c = '13;14',
				Grades_Served__c = '7;8',
                Genders_Served__c = 'Female'
			)
		);
        jobs.add(
			new Launchpad__Job__c(
				Name = 'Test Job Name Search',
				Launchpad__Account__c = accounts[0].Id,
				Launchpad__Available_in_Community__c = true,
				Program__c = program.Id,
				Launchpad__Job_Description__c = 'Test Description 4',
				Ages_Served__c = '13;14',
				Grades_Served__c = '9;10',
                Genders_Served__c = 'Male'
			)
		);
		insert jobs;
	}

    @IsTest
    static void testSearchByZipCode() {
		Test.startTest();
        List<Launchpad__Job__c> jobs = ProviderSearchController.searchJobsDynamic(
            '19104',
            null,
            null,
			null
        );
		Test.stopTest();
        Assert.areEqual(1, jobs.size());
        Assert.areEqual('Test Job Zip 19104', jobs[0].Name);
    }

	@IsTest
	static void testSearchByJobSiteAddress() {
		Test.startTest();
		List<Launchpad__Job__c> jobs = ProviderSearchController.searchJobsDynamic(
				null,
				null,
				new Map<String, String>{
						'Name' => 'Test Job Name'
				},
				null
		);
		Test.stopTest();
		Assert.areEqual(1, jobs.size());
		Assert.areEqual('Test Job Name Search', jobs[0].Name);
	}

	@IsTest
	static void testSearchByGradeAndAge() {
		Test.startTest();
		List<Launchpad__Job__c> jobs = ProviderSearchController.searchJobsDynamic(
				null,
				new List<String>{ 'Ages_Served__c', 'Grades_Served__c' },
				null,
				new Map<String, String[]>{
						'Ages_Served__c' => new String[]{ '12' },
						'Grades_Served__c' => new String[]{ '7', '8' }
				}
		);
		Test.stopTest();
		Assert.areEqual(1, jobs.size());
		Assert.areEqual('Test Job 1', jobs[0].Name);
	}

	@IsTest
	static void testGettingFieldSetMembers() {
		Test.startTest();
		ProviderSearchController.FieldData[] fieldData =
				ProviderSearchController.getJobFieldSetMembers('Launchpad__Advanced_Job_Search_Filters');
		Test.stopTest();
		Assert.isTrue(!fieldData.isEmpty());
	}

	@IsTest
	static void testGettingContactJobEligibilityMaps() {
		Test.startTest();
		ProviderSearchController.getContactJobEligibilityMaps();
		Test.stopTest();
	}

	@IsTest
	static void testGetFieldDataByObjectAndFieldNames() {
		Test.startTest();
		ProviderSearchController.getFieldDataByObjectAndFieldNames('Launchpad__Job__c', new String[]{ 'Schools_Served__c' });
		Test.stopTest();
	}

	@IsTest
	static void testGetCurrentUsersContactFields() {
		Test.startTest();
		ProviderSearchController.getCurrentUsersContactFieldValues(new String[]{ 'School__c '});
		Test.stopTest();
	}

}