force-app/main/default/objects/Contact/fields/Emergency_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_Email__c</fullName>
    <label>Emergency Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Guardian_Email__c.field-meta.xml
<CustomField>
    <fullName>Guardian_Email__c</fullName>
    <label>Guardian Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/Launchpad__Applicant_Tracking__c.object-meta.xml
<CustomObject>
    <description>This Object is used by Job Seekers to apply for Jobs in the system.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>App-{0}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Date_of_Birth_MM_DD_YYYY__c.field-meta.xml
<CustomField>
    <fullName>Applicant_s_Date_of_Birth_MM_DD_YYYY__c</fullName>
    <label>Applicant&apos;s Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Applicant_s_Email_Address__c</fullName>
    <inlineHelpText>Email address for the applicant</inlineHelpText>
    <label>Applicant&apos;s Email Address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicants_Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Applicants_Tax_Id__c</fullName>
    <inlineHelpText>Enter your Social Security Number as 9 digits</inlineHelpText>
    <label>Applicants Social Security Number</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Emergency_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_Email__c</fullName>
    <label>Emergency Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Guardian_Consent_Required__c.field-meta.xml
<CustomField>
    <fullName>Guardian_Consent_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Guardian Consent Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Guardian_Email__c.field-meta.xml
<CustomField>
    <fullName>Guardian_Email__c</fullName>
    <label>Guardian Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Launchpad__Stage__c.field-meta.xml
<CustomField>
    <fullName>Launchpad__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
                <default>true</default>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Provider Selected</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Matched with Provider</fullName>
            </value>
            <value>
                <fullName>Ready for JEVs Sign-Off</fullName>
            </value>
            <value>
                <fullName>Placed</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Potential Match</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Previous_Stage__c.field-meta.xml
<CustomField>
    <fullName>Previous_Stage__c</fullName>
    <label>Previous Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Provider Selected</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Matched with Provider</fullName>
            </value>
            <value>
                <fullName>Ready for JEVs Sign-Off</fullName>
            </value>
            <value>
                <fullName>Placed</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Provider_Rank__c.field-meta.xml
<CustomField>
    <fullName>Provider_Rank__c</fullName>
    <label>Provider Rank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Submitted_From_Universal_App__c.field-meta.xml
<CustomField>
    <fullName>Submitted_From_Universal_App__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submitted From Universal App</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Launchpad__Job__c/Launchpad__Job__c.object-meta.xml
<CustomObject>
    <description>This Object is used by Employers to create Job positions that are open for hire.</description>
    <label>Job</label>
    <nameField>
        <label>Job Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ConsentFormBatchEmailTest.cls
@isTest
public class ConsentFormBatchEmailTest {
    @testSetup
    static void setupTestData() {
         Account testAccount = new Account(
            Name = 'Test Account',
            Industry = 'Technology',  
            Phone = '123-456-7890' 
        );
        insert testAccount;
        
        List<Contact> contacts = new List<Contact>();
        for (Integer i = 0; i < 5; i++) {
            contacts.add(new Contact(FirstName = 'Test', LastName = 'Participant ' + i));
        }
        insert contacts;

        List<Launchpad__Applicant_Tracking__c> jobApplications = new List<Launchpad__Applicant_Tracking__c>();
        
        Launchpad__Job__c job = new Launchpad__Job__c();
        job.Launchpad__Openings__c = 10;
        job.Launchpad__Account__c = testAccount.Id;
        job.Launchpad__Stage__c = 'Interviewing';
        job.Launchpad__Closing_Date__c = Date.today();
        job.Launchpad__Source__c = 'Direct Employer Contact';
        job.Launchpad__Hourly_Wage_Minimum__c = 30.00;
        job.Launchpad__Hourly_Wage_Maximum__c = 60.00;
        
        insert job;
        
        
        Launchpad__Applicant_Tracking__c firstApp = new Launchpad__Applicant_Tracking__c();
        firstApp.Launchpad__Participant__c = contacts[0].Id; 
        firstApp.Launchpad__Stage__c = 'Submitted';
        firstApp.Provider_Rank__c = '1';
        firstApp.Previous_Stage__c = 'Provider Selected';
        firstApp.Launchpad__Job_Order__c = job.Id;
        firstApp.Applicant_s_Email_Address__c = 'Test12@test12345.com';
        firstApp.guardian_consent_required__c = true;
        firstApp.Applicants_Tax_Id__c = '332-65-7823';
        firstApp.submitted_from_universal_app__c = true;
        firstApp.Emergency_Contact_Email__c = 'egeeggbrnrn@fwewgreeffe.com';
        firstApp.guardian_email__c = 'Test3423322324242424244224@test4gfdwegegf.com';
        firstApp.Applicant_s_Date_of_Birth_MM_DD_YYYY__c = Date.ValueOf('2008-03-03');
        jobApplications.add(firstApp);

            
        
        
        insert jobApplications;
    }
    @isTest
    public static void testBatch(){
        List<Launchpad__Applicant_Tracking__c> jobApplications = [SELECT Id, Launchpad__Participant__c, Launchpad__Stage__c, Previous_Stage__c, Provider_Rank__c FROM Launchpad__Applicant_Tracking__c ORDER BY Provider_Rank__c];
        List<List<Id>> t = new List<List<Id>>();
        List<Id> tempList = new List<Id>();
        for(Launchpad__Applicant_Tracking__c l : jobApplications){
            tempList.add(l.Id);
        }
        t.add(tempList);
        JobApplicationConsentFormController.sendConsentFormEmail(t);
    }
}