force-app/main/default/objects/Launchpad__Applicant_Tracking__c/Launchpad__Applicant_Tracking__c.object-meta.xml
<CustomObject>
    <description>This Object is used by Job Seekers to apply for Jobs in the system.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>App-{0}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_City__c.field-meta.xml
<CustomField>
    <fullName>Applicant_City__c</fullName>
    <label>Applicant&apos;s City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Date_of_Birth_MM_DD_YYYY__c.field-meta.xml
<CustomField>
    <fullName>Applicant_s_Date_of_Birth_MM_DD_YYYY__c</fullName>
    <label>Applicant&apos;s Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Applicant_s_Email_Address__c</fullName>
    <inlineHelpText>Email address for the applicant</inlineHelpText>
    <label>Applicant&apos;s Email Address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_State__c.field-meta.xml
<CustomField>
    <fullName>Applicant_s_State__c</fullName>
    <label>Applicant&apos;s State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Applicant_s_Street_Address__c</fullName>
    <label>Applicant&apos;s Street Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Applicant_s_Zip_Code__c</fullName>
    <label>Applicant&apos;s Zip Code</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Launchpad__Stage__c.field-meta.xml
<CustomField>
    <fullName>Launchpad__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
                <default>true</default>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Provider Selected</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Matched with Provider</fullName>
            </value>
            <value>
                <fullName>Ready for JEVs Sign-Off</fullName>
            </value>
            <value>
                <fullName>Placed</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Potential Match</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Launchpad__Program__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Provider_Rank__c.field-meta.xml
<CustomField>
    <fullName>Provider_Rank__c</fullName>
    <label>Provider Rank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Launchpad__Job__c/Launchpad__Job__c.object-meta.xml
<CustomObject>
    <description>This Object is used by Employers to create Job positions that are open for hire.</description>
    <label>Job</label>
    <nameField>
        <label>Job Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Launchpad__Job__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Launchpad__Program__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Launchpad__Program__c/Launchpad__Program__c.object-meta.xml
<CustomObject>
    <description>This Object is used to track programs awarded to the organization i.e. WIOA Adult, TAA, etc.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Launchpad__Program__c/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

force-app/main/default/classes/CreateApplicationController.cls
public with sharing class CreateApplicationController {
	/**
	 * Create a new application for a contact and job.
	 * @param contactId The contact ID.
	 * @param jobId The job ID.
	 * @return The ID of the new application.
	 */
	@AuraEnabled
	public static Id createApplication(String contactId, String jobId, String contactEmail) {
		try {
			// If youth already has an application for this job in an active program, return the existing application ID.
			List<Launchpad__Applicant_Tracking__c> existingApplications = [
				SELECT Id
				FROM Launchpad__Applicant_Tracking__c
				WHERE
					Launchpad__Participant__c = :contactId
					AND Launchpad__Job_Order__c = :jobId
					AND Program__r.Launchpad__Active__c = 'Yes'
					AND Program__r.RecordType.Name = 'Session'
			];
			if (!existingApplications.isEmpty()) {
				return existingApplications[0].Id;
			}

			Launchpad__Job__c job = [SELECT Id, Program__c FROM Launchpad__Job__c WHERE Id = :jobId];

			Launchpad__Applicant_Tracking__c application = new Launchpad__Applicant_Tracking__c(
				Launchpad__Participant__c = contactId,
				Launchpad__Job_Order__c = jobId,
				Provider_Rank__c = '1',
				Applicant_s_Email_Address__c = contactEmail,
				Launchpad__Stage__c = 'In Progress',
				Program__c = job.Program__c
			);
			insert application;
			return application.Id;
		} catch (Exception e) {
			System.debug('Error creating application: ' + e.getMessage());
			throw e;
		}
	}

	@AuraEnabled
	public static Id createBulkApplications(
		String contactId,
		String contactEmail,
		List<Map<String, Object>> applications
	) {
		try {
			List<Id> jobIds = new List<Id>();
			for (Map<String, Object> app : applications) {
				jobIds.add((String) app.get('id'));
			}

			// If applicant already has an application in the active program session, return the existing application ID.
			List<Launchpad__Applicant_Tracking__c> existingApplications = [
				SELECT Id
				FROM Launchpad__Applicant_Tracking__c
				WHERE
					Launchpad__Participant__c = :contactId
					AND Launchpad__Job_Order__c IN :jobIds
					AND Program__r.Launchpad__Active__c = 'Yes'
					AND Program__r.RecordType.Name = 'Session'
			];
			if (!existingApplications.isEmpty()) {
				throw new AuraHandledException('You have already applied to a program in this session.');
			}

			Launchpad__Job__c job = [SELECT Id, Program__c FROM Launchpad__Job__c WHERE Id = :jobIds[0]];
            
            Contact con = [SELECT Id, MailingCity, MailingStreet, MailingState, MailingPostalCode, Birthdate FROM Contact WHERE Id = :contactId];

			List<Launchpad__Applicant_Tracking__c> newApplications = new List<Launchpad__Applicant_Tracking__c>();
			for (Map<String, Object> app : applications) {
                
                Integer postalCode = null;
                                
                if(con.MailingPostalCode != null){
                    postalCode = Integer.valueOf(con?.MailingPostalCode);
                }
                
                if(con.Birthdate != null){
                    
                }
                
				Launchpad__Applicant_Tracking__c application = new Launchpad__Applicant_Tracking__c(
                    Applicant_s_Street_Address__c = con?.MailingStreet,
                    Applicant_City__c = con?.MailingCity,
                    Applicant_s_State__c = con?.MailingState,
                    Applicant_s_Zip_Code__c = postalCode,
                    Applicant_s_Date_of_Birth_MM_DD_YYYY__c  = con?.Birthdate,
					Launchpad__Participant__c = contactId,
					Launchpad__Job_Order__c = (String) app.get('id'),
					Provider_Rank__c = (String) app.get('order'),
					Applicant_s_Email_Address__c = contactEmail,
					Launchpad__Stage__c = 'In Progress',
					Program__c = job.Program__c
				);
				newApplications.add(application);
			}

			insert newApplications;
			return newApplications[0].Id;
		} catch (Exception e) {
			System.debug('Error creating application: ' + e.getMessage());
			throw e;
		}
	}

	@AuraEnabled
	public static List<Launchpad__Applicant_Tracking__c> getContactApplications(Id contactId) {
		try {
			List<Launchpad__Applicant_Tracking__c> applications = [
				SELECT Id, Launchpad__Stage__c, Launchpad__Job_Order__r.Name, Provider_Rank__c
				FROM Launchpad__Applicant_Tracking__c
				WHERE
					Launchpad__Participant__c = :contactId
					AND Program__r.Launchpad__Active__c = 'Yes'
					AND Program__r.RecordType.Name = 'Session'
			];

            return applications;
		} catch (Exception e) {
			System.debug('Error getting applications: ' + e.getMessage());
			throw e;
		}
	}

    @AuraEnabled
    public static Boolean hasActiveApplication(Id contactId) {
        try {
            List<Launchpad__Applicant_Tracking__c> applications = [
                SELECT Id
                FROM Launchpad__Applicant_Tracking__c
                WHERE
                    Launchpad__Participant__c = :contactId
                    AND Program__r.Launchpad__Active__c = 'Yes'
                    AND Program__r.RecordType.Name = 'Session'
            ];

            return !applications.isEmpty();
        } catch (Exception e) {
            System.debug('Error getting applications: ' + e.getMessage());
            throw e;
        }
    }
}