force-app/main/default/objects/Launchpad__Applicant_Tracking__c/Launchpad__Applicant_Tracking__c.object-meta.xml
<CustomObject>
    <description>This Object is used by Job Seekers to apply for Jobs in the system.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>App-{0}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Legal_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_s_Legal_First_Name__c</fullName>
    <formula>Launchpad__Participant__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>As it appears on Birth Cert</inlineHelpText>
    <label>Applicant&apos;s Legal First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Legal_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_s_Legal_Last_Name__c</fullName>
    <formula>Launchpad__Participant__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant&apos;s Legal Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Consent_to_Request_Clearance__c.field-meta.xml
<CustomField>
    <fullName>Consent_to_Request_Clearance__c</fullName>
    <inlineHelpText>I give permission to the C2L-PHL and its contracted agencies, partners and funders to run criminal, Child abuse and FBI clearances, if and only if, needed for the position I am assigned.</inlineHelpText>
    <label>Consent to Request Clearance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
                <isActive>false</isActive>
                <label>Not Applicable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Guardian_Consent_Required__c.field-meta.xml
<CustomField>
    <fullName>Guardian_Consent_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Guardian Consent Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Media_Picture_Release__c.field-meta.xml
<CustomField>
    <fullName>Media_Picture_Release__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media &amp; Picture Release</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Parent_s_Consent__c.field-meta.xml
<CustomField>
    <fullName>Parent_s_Consent__c</fullName>
    <label>Parent&apos;s Consent</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Release_of_Information__c.field-meta.xml
<CustomField>
    <fullName>Release_of_Information__c</fullName>
    <inlineHelpText>I give my permission for C2L-PHL and its contracted agencies, partners and funders to release information concerning my participation in the program. I understand that all information will be kept respectfully confidential but the sharing of this information within and among these agencies may be necessary.</inlineHelpText>
    <label>Release of Information</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/consentFormGuestController.cls
public without sharing class consentFormGuestController {
    
    @AuraEnabled(cacheable=false)
    public static void updateSingleJobApplication(Launchpad__Applicant_Tracking__c appToUpdate){
        appToUpdate.Guardian_Consent_Required__c = false;
          update appToUpdate;    
    }

    
    @AuraEnabled(cacheable=true)
    public static Launchpad__Applicant_Tracking__c getCurrentJobApplication(Id appId){
        System.debug('app.Id: ' + appId);
            return [SELECT Id, Applicant_s_Legal_First_Name__c, Applicant_s_Legal_Last_Name__c, Media_Picture_Release__c, Parent_s_Consent__c, Release_of_Information__c, Consent_to_Request_Clearance__c, Guardian_Consent_Required__c 
                FROM Launchpad__Applicant_Tracking__c
                WHERE Id = :appId
                LIMIT 1
            ];
        }
}