force-app/main/default/objects/Launchpad__Applicant_Tracking__c/Launchpad__Applicant_Tracking__c.object-meta.xml
<CustomObject>
    <description>This Object is used by Job Seekers to apply for Jobs in the system.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>App-{0}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Consent_to_Request_Clearance__c.field-meta.xml
<CustomField>
    <fullName>Consent_to_Request_Clearance__c</fullName>
    <inlineHelpText>I give permission to the C2L-PHL and its contracted agencies, partners and funders to run criminal, Child abuse and FBI clearances, if and only if, needed for the position I am assigned.</inlineHelpText>
    <label>Consent to Request Clearance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
                <isActive>false</isActive>
                <label>Not Applicable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Guardian_Consent_Required__c.field-meta.xml
<CustomField>
    <fullName>Guardian_Consent_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Guardian Consent Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Media_Picture_Release__c.field-meta.xml
<CustomField>
    <fullName>Media_Picture_Release__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media &amp; Picture Release</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Parent_s_Consent__c.field-meta.xml
<CustomField>
    <fullName>Parent_s_Consent__c</fullName>
    <label>Parent&apos;s Consent</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Launchpad__Program__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Release_of_Information__c.field-meta.xml
<CustomField>
    <fullName>Release_of_Information__c</fullName>
    <inlineHelpText>I give my permission for C2L-PHL and its contracted agencies, partners and funders to release information concerning my participation in the program. I understand that all information will be kept respectfully confidential but the sharing of this information within and among these agencies may be necessary.</inlineHelpText>
    <label>Release of Information</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GuestUserApplicationController.cls
public without sharing class GuestUserApplicationController {
    
    public static Launchpad__Applicant_Tracking__c getCurrentJobApplication(Id appId){
        return [SELECT Id, Media_Picture_Release__c, Guardian_Consent_Required__c, Parent_s_Consent__c, Release_of_Information__c, Consent_to_Request_Clearance__c, Program__c, Launchpad__Participant__c 
			FROM Launchpad__Applicant_Tracking__c
			WHERE Id = :appId
			LIMIT 1
		];
    }
    
    public static List<Launchpad__Applicant_Tracking__c> getRelatedJobApplications(Id appId){
        Launchpad__Applicant_Tracking__c currentApp = getCurrentJobApplication(appId);
        
        return [SELECT Id, Media_Picture_Release__c, Parent_s_Consent__c, Release_of_Information__c, Consent_to_Request_Clearance__c, Program__c, Launchpad__Participant__c
                FROM Launchpad__Applicant_Tracking__c
				WHERE Program__c = :currentApp.Program__c
				AND Launchpad__Participant__c = :currentApp.Launchpad__Participant__c];
    }
    
    public static List<Database.UpsertResult> updateJobApplications(List<Launchpad__Applicant_Tracking__c> appsToUpdate){
        System.debug('Inside update app');
         List<Database.UpsertResult> result = Database.upsert(appsToUpdate, false);
        System.debug('Result: ' + result);
         return result;
    }
    
    public static Database.UpsertResult updateSingleJobApplication(sObject appToUpdate){
         Database.UpsertResult result = Database.upsert(appToUpdate, false);
         return result;
    }
    
     public static void sendConsentFormEmail(String guardianEmail, Id appId){
        System.debug('In send semail method');
		Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        List<String> toAddresses = new List<String>();
        toAddresses.add(guardianEmail);
        mail.setToAddresses(toAddresses);  
        
        mail.setSubject('Test Email from Apex'); 
        
        String href = 'https://philaworks--developer.sandbox.my.site.com/youth/s/consentform?recordId=' + String.valueOf(appId) ;
        String emailBody = 'Here is a test body.';
        emailBody += '<a href='+href+' target=_blank>Click here</a><br><br>';
        mail.setHTMLBody(emailBody);  

        System.debug('guardianEmail: ' + guardianEmail);
        System.debug('toAddresses: ' + toAddresses);
        System.debug('emailBody: ' + emailBody);
        System.debug('appId: ' + appId);
        
        try{
            Messaging.sendEmail(new Messaging.Email[] { mail });
        }catch(exception e){
            System.debug('Error sending email: ' + e);
        }
            
        
    }
}